---
packages:
- name: java_for_riemanntools
  version: !binary |-
    NjRmMDliM2VhYzUwZGNhOGM2ZjQ4ZjU3ZDg1ODMzZjFjMTVmM2Q3ZA==
  fingerprint: !binary |-
    NjRmMDliM2VhYzUwZGNhOGM2ZjQ4ZjU3ZDg1ODMzZjFjMTVmM2Q3ZA==
  sha1: !binary |-
    NTlkZjA0OWI1NzAwYTljNzc5MmFmOGIxN2JjNTA0ZDBlNWIwZGIxZg==
  dependencies: []
- name: riemann-cassandra
  version: !binary |-
    ODBhMTQ2NDE5M2RhOTY2NDg0OTFmN2QwNTJiMDNiNTBmYWI4MGVjMg==
  fingerprint: !binary |-
    ODBhMTQ2NDE5M2RhOTY2NDg0OTFmN2QwNTJiMDNiNTBmYWI4MGVjMg==
  sha1: !binary |-
    ZTM0NTIwYmYwYzk0YzIyNjUwZmYxZTljYzRhODg2MmIxMmMxNWQ4Mg==
  dependencies: []
- name: riemann-mongodb
  version: !binary |-
    YWZlOWJiZmJmZjhhMDAxMzQzZThlZmQ5M2MzZGUzMzZlYzMwNTAwMA==
  fingerprint: !binary |-
    YWZlOWJiZmJmZjhhMDAxMzQzZThlZmQ5M2MzZGUzMzZlYzMwNTAwMA==
  sha1: !binary |-
    N2I1ZTEzNmY5MDFlMTJmNWQ2YzA0MzMzMTE3M2U5ZmMyNzg3MWFmZA==
  dependencies:
  - ruby
- name: riemann-redis
  version: !binary |-
    MDMzOWRiOTljYTkzZTY0ZTkzNGYxMTZiMmUyMjczZDM0YzE2ZjNlYQ==
  fingerprint: !binary |-
    MDMzOWRiOTljYTkzZTY0ZTkzNGYxMTZiMmUyMjczZDM0YzE2ZjNlYQ==
  sha1: !binary |-
    Njc5ZjViMzE0NjJiNTY0ODQ3MzJkMjhmZTkzNmU2Nzk5ODNkMjlkOQ==
  dependencies:
  - ruby
- name: riemann-tools
  version: !binary |-
    ODJmM2JkMGEwZTk1ZjdhMWI1YWNjN2MzZjExMTk0N2M1YTY1MjQ1OQ==
  fingerprint: !binary |-
    ODJmM2JkMGEwZTk1ZjdhMWI1YWNjN2MzZjExMTk0N2M1YTY1MjQ1OQ==
  sha1: !binary |-
    ZGRhZjIzZTMzMDQ4OWY1YTAzOTJiMWM0ZTI4MDZkZmQ3MjY1NjRlOA==
  dependencies:
  - ruby
- name: ruby
  version: !binary |-
    OWI1OWQyZjI3MDBkYTgxYTk4YzM4YzczY2QyN2I2Y2NmMjZmMTg4Yw==
  fingerprint: !binary |-
    OWI1OWQyZjI3MDBkYTgxYTk4YzM4YzczY2QyN2I2Y2NmMjZmMTg4Yw==
  sha1: !binary |-
    YmNhMDAzZWM0N2M3MWQzMTRiOGMxZjBiZjk0Y2YxZGRiM2ZiZDg2OA==
  dependencies: []
jobs:
- name: riemann-cassandra
  version: !binary |-
    ZDc1MGEyOGVkMDI3M2I0ZWE5MDM5OTY2NDlhMTY1MGEzNWEwMDczNQ==
  fingerprint: !binary |-
    ZDc1MGEyOGVkMDI3M2I0ZWE5MDM5OTY2NDlhMTY1MGEzNWEwMDczNQ==
  sha1: !binary |-
    YjlmYzg3ZWZjM2UxYWEyYjE3NGNiYWE0ZTI2Nzk1YjAwOTY5ZTE5Mw==
- name: riemann-disk
  version: !binary |-
    ZTgzMTM4NzU2NjBhMGEwZmUwMmI5NGYyZjg4MDRlZGI3YmE5ZjhkNQ==
  fingerprint: !binary |-
    ZTgzMTM4NzU2NjBhMGEwZmUwMmI5NGYyZjg4MDRlZGI3YmE5ZjhkNQ==
  sha1: !binary |-
    OTU0MGNlYTEzYzQ0Yjg2YmQ4MDI0YWIwZDY1MzQyZTk2ODc0ODVjOQ==
- name: riemann-elasticsearch
  version: !binary |-
    OWY2YjMyYjc4MjA4OTA1OWIzNmQxZGJiODM4YThkZTU4ZDhkMDU5ZA==
  fingerprint: !binary |-
    OWY2YjMyYjc4MjA4OTA1OWIzNmQxZGJiODM4YThkZTU4ZDhkMDU5ZA==
  sha1: !binary |-
    ODU2MTAxYTE1MjM0YjQwOGQxY2I3MzdmMTNmOTNiYmZkNzYyYTJjNA==
- name: riemann-mongodb
  version: !binary |-
    NDU0NzJjMjhjMGU4YmJiYzdhMzA3YjY4YzdmYWFjMmY2YWU4OTNhZg==
  fingerprint: !binary |-
    NDU0NzJjMjhjMGU4YmJiYzdhMzA3YjY4YzdmYWFjMmY2YWU4OTNhZg==
  sha1: !binary |-
    N2E4NTkzMWNmOGE2YzhkZTA2ODM3OWEzMDEwMWNhYzQzOGY4Nzc4ZQ==
- name: riemann-redis
  version: !binary |-
    YTM4MjA2M2ZhZDhmZGQ4ZmVmZWU0ODliM2U5NWNiYWQ5ZTRiYWFmZA==
  fingerprint: !binary |-
    YTM4MjA2M2ZhZDhmZGQ4ZmVmZWU0ODliM2U5NWNiYWQ5ZTRiYWFmZA==
  sha1: !binary |-
    MWJhZjAxZTE1NmUxMDI4ODI1MzYwNjVlMzU2YzFiMTQ0NDgzYzk5ZQ==
- name: riemann-tools
  version: !binary |-
    MDM2MzYzZThkMDY1MTIyMjk4OTgwODQxNzNlYzIzNTI1YzNkYmQ5Zg==
  fingerprint: !binary |-
    MDM2MzYzZThkMDY1MTIyMjk4OTgwODQxNzNlYzIzNTI1YzNkYmQ5Zg==
  sha1: !binary |-
    ODhhZTRlNWIwMmUyZmRkZGU1N2FiYzhiOGVlNThhMzBkZGY5YWY3NA==
- name: riemann-zookeeper
  version: !binary |-
    ZDhlYzU3YjE4ZDc2NmRhZDA3YmI4NzA5N2MxNzViZGNiYzhkMTU3Mg==
  fingerprint: !binary |-
    ZDhlYzU3YjE4ZDc2NmRhZDA3YmI4NzA5N2MxNzViZGNiYzhkMTU3Mg==
  sha1: !binary |-
    ZTIxOTk1MzkxYzg5ODQ5Mjc0ZTNhZmE4ZWJiMzMxNDIwZDliOWU1ZQ==
license:
  version: !binary |-
    NTY5YTQ4MTY2M2Y5NWIxMGNiODAzNTM5YmE2MWE4YzI0YTg4MTQ2Mw==
  fingerprint: !binary |-
    NTY5YTQ4MTY2M2Y5NWIxMGNiODAzNTM5YmE2MWE4YzI0YTg4MTQ2Mw==
  sha1: !binary |-
    ZDY3ODU4ZjI5YmM5NjA2NzI5NDYwNjBmOWNlNDBhYjYxYTA3ZjM0MQ==
commit_hash: efc79cc0
uncommitted_changes: true
name: riemanntools
version: 0.6.0
